#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -std=c++11 -D_REENTRANT
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.assignment4
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ./
BIN           = $(BTARGETDIR)assignment4$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O
LDLIBS        = -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = composite_Calculator/Add_Expr_Node$(OBJEXT) composite_Calculator/Divide_Expr_Node$(OBJEXT) composite_Calculator/Mod_Expr_Node$(OBJEXT) composite_Calculator/Multiply_Expr_Node$(OBJEXT) composite_Calculator/Sub_Expr_Node$(OBJEXT) composite_Calculator/Number_Expr_Node$(OBJEXT) composite_Calculator/Unary_Expr_Node$(OBJEXT) composite_Calculator/Parenthesis_Node$(OBJEXT) composite_Calculator/Expr_Tree$(OBJEXT) composite_Calculator/Binary_Expr_Node$(OBJEXT) composite_Calculator/Calculator$(OBJEXT) composite_Calculator/Eval_Expr_Tree$(OBJEXT) composite_Calculator/Expr_Builder$(OBJEXT) composite_Calculator/Expr_Node_Visitor$(OBJEXT) composite_Calculator/Expr_Node$(OBJEXT) composite_Calculator/Expr_Tree_Builder$(OBJEXT) composite_Calculator/Print_Inorder_Expression$(OBJEXT) composite_Calculator/Node_Command_Factory$(OBJEXT) composite_Calculator/Stack_Node_Factory$(OBJEXT) driver$(OBJEXT)
SRC           = composite_Calculator/Add_Expr_Node.cpp composite_Calculator/Divide_Expr_Node.cpp composite_Calculator/Mod_Expr_Node.cpp composite_Calculator/Multiply_Expr_Node.cpp composite_Calculator/Sub_Expr_Node.cpp composite_Calculator/Number_Expr_Node.cpp composite_Calculator/Unary_Expr_Node.cpp composite_Calculator/Parenthesis_Node.cpp composite_Calculator/Expr_Tree.cpp composite_Calculator/Binary_Expr_Node.cpp composite_Calculator/Calculator.cpp composite_Calculator/Eval_Expr_Tree.cpp composite_Calculator/Expr_Builder.cpp composite_Calculator/Expr_Node_Visitor.cpp composite_Calculator/Expr_Node.cpp composite_Calculator/Expr_Tree_Builder.cpp composite_Calculator/Print_Inorder_Expression.cpp composite_Calculator/Node_Command_Factory.cpp composite_Calculator/Stack_Node_Factory.cpp driver.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 
DEPLIBS       = $(foreach lib, , $(foreach libpath, ., $(wildcard $(libpath)/lib$(lib).a)))

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BIN): $(OBJS) $(DEPLIBS)
	@$(TESTDIRSTART) "$(BTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(BTARGETDIR)"
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

composite_Calculator/Add_Expr_Node$(OBJEXT): composite_Calculator/Add_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Add_Expr_Node.cpp

composite_Calculator/Divide_Expr_Node$(OBJEXT): composite_Calculator/Divide_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Divide_Expr_Node.cpp

composite_Calculator/Mod_Expr_Node$(OBJEXT): composite_Calculator/Mod_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Mod_Expr_Node.cpp

composite_Calculator/Multiply_Expr_Node$(OBJEXT): composite_Calculator/Multiply_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Multiply_Expr_Node.cpp

composite_Calculator/Sub_Expr_Node$(OBJEXT): composite_Calculator/Sub_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Sub_Expr_Node.cpp

composite_Calculator/Number_Expr_Node$(OBJEXT): composite_Calculator/Number_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Number_Expr_Node.cpp

composite_Calculator/Unary_Expr_Node$(OBJEXT): composite_Calculator/Unary_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Unary_Expr_Node.cpp

composite_Calculator/Parenthesis_Node$(OBJEXT): composite_Calculator/Parenthesis_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Parenthesis_Node.cpp

composite_Calculator/Expr_Tree$(OBJEXT): composite_Calculator/Expr_Tree.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Expr_Tree.cpp

composite_Calculator/Binary_Expr_Node$(OBJEXT): composite_Calculator/Binary_Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Binary_Expr_Node.cpp

composite_Calculator/Calculator$(OBJEXT): composite_Calculator/Calculator.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Calculator.cpp

composite_Calculator/Eval_Expr_Tree$(OBJEXT): composite_Calculator/Eval_Expr_Tree.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Eval_Expr_Tree.cpp

composite_Calculator/Expr_Builder$(OBJEXT): composite_Calculator/Expr_Builder.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Expr_Builder.cpp

composite_Calculator/Expr_Node_Visitor$(OBJEXT): composite_Calculator/Expr_Node_Visitor.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Expr_Node_Visitor.cpp

composite_Calculator/Expr_Node$(OBJEXT): composite_Calculator/Expr_Node.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Expr_Node.cpp

composite_Calculator/Expr_Tree_Builder$(OBJEXT): composite_Calculator/Expr_Tree_Builder.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Expr_Tree_Builder.cpp

composite_Calculator/Print_Inorder_Expression$(OBJEXT): composite_Calculator/Print_Inorder_Expression.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Print_Inorder_Expression.cpp

composite_Calculator/Node_Command_Factory$(OBJEXT): composite_Calculator/Node_Command_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Node_Command_Factory.cpp

composite_Calculator/Stack_Node_Factory$(OBJEXT): composite_Calculator/Stack_Node_Factory.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) composite_Calculator/Stack_Node_Factory.cpp

driver$(OBJEXT): driver.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) driver.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) -Wall -Wextra -pedantic -fsyntax-only $(CHK_SOURCES)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------


depend:
	-$(MPC_ROOT)/depgen.pl  $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

-include $(DEPENDENCIES)
